.Dd September 26, 2022
.Dt CWDOF 1
.Os
.Sh NAME
.Nm cwdof
.Nd get the current working directory of a process
.Sh SYNOPSIS
.Nm
.Ar pid
.Sh DESCRIPTION
.Nm
receives as single argument the pid (proces ID) of a process,
and prints to standard output the current working directory of this process.
.Sh SEE ALSO
.Xr ps 1 ,
.Xr sysctl 2
